routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //Session::flush();
    return redirect('/login');
});

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::group([
    'prefix' => 'admin',
    'namespace' => 'User',
], function () {
    Route::resource('user', 'UserController');

    Route::get('/level', 'levelController@index')->name('level.index');
    Route::post('/level', 'levelController@store')->name('level.store');
    Route::get('/level/{id}', 'levelController@edit')->name('level.edit');
    Route::put('/level/{id}', 'levelController@update')->name('level.update');
    Route::delete('/level/{id}', 'levelController@delete')->name('level.delete');
});

Route::group([
    'prefix' => 'inventory',
    'namespace' => 'Inventory',
], function () {
    Route::get('/index', 'equipmentController@index')->name('inventory.index');
    Route::get('/index/{serial}', 'equipmentController@find')->name('inventory.find');
    Route::get('/create', 'equipmentController@create')->name('inventory.create');
    Route::get('/edit', 'equipmentController@edit')->name('inventory.edit');
    Route::post('/store', 'equipmentController@store')->name('inventory.store');
    Route::post('/index', 'equipmentController@search')->name('inventory.search');
    Route::post('/index/sector', 'equipmentController@findSector')->name('inventory.sector');
});

app/Http/Controllers/Controller.php
<?php

namespace InvOco\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace InvOco\Http\Controllers;

use Illuminate\Http\Request;
use InvOco\Http\Services\Charts;
use InvOco\Http\Services\Metrics;

class DashboardController extends Controller
{
    /**
     * @var Metrics
     * @var Charts
     */
    private $metrics;
    private $charts;

    /**
     * DashboardController constructor.
     * @param Metrics $metrics
     * @param Charts $charts
     */
    public function __construct(Metrics $metrics, Charts $charts)
    {
        $this->metrics = $metrics;
        $this->charts = $charts;
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     * @param Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return view('dashboard', with([
            'equipmentsCount' => $this->metrics->countEquipments(),
            'occurrencesCount' => $this->metrics->countOccurrences(),
            'reportsCount' => $this->metrics->countOccurrences(),
            'usersCount' => $this->metrics->countUsers(),
            'yearOccurrences' => $this->metrics->countOccurrencesYear(),
            'yearEquipments' => $this->metrics->countEquipmentsYear(),
            'occurrenceChart' => $this->charts->occurencesChart(),
            'equipmentChart' => $this->charts->equipmentsChart(),
        ]));
    }
}

app/Http/Controllers/Inventory/EquipmentController.php
<?php

namespace InvOco\Http\Controllers\Inventory;

use Illuminate\Http\Request;
use InvOco\Http\Controllers\Controller;
use InvOco\Repositories\Models\Equipment;
use InvOco\Http\Services\Equipment as SEquipment;
use InvOco\Repositories\EquipmentsRepository;
use InvOco\Repositories\Models\Sector;
use InvOco\Repositories\Models\TypeEquipment;
use InvOco\Repositories\RoomRepository;

class EquipmentController extends Controller
{
    private $equipmentsRepository;
    private $roomRepository;
    private $equipment;

    public function __construct(EquipmentsRepository $equipmentsRepository, SEquipment $equipment, RoomRepository $roomRepository)
    {
        $this->equipmentsRepository = $equipmentsRepository;
        $this->equipment = $equipment;
        $this->roomRepository = $roomRepository;
    }

    public function index()
    {
        $equipment = new Equipment();
        $sector = (new Sector())->all();
        $all = $equipment->all();

        return view('inventory.inventory_index', with([
            'equipment' => $equipment,
            'sectors' => $sector,
            'equipments' => $all,
        ]));
    }

    public function create()
    {
        $equipment = new Equipment();
        $type = (new TypeEquipment())->all();

        $sector = (new Sector())->all();

        return view('inventory.inventory_create', with([
            'equipment' => $equipment,
            'sector' => $sector,
            'type' => $type,
        ]));
    }

    public function store(Request $request)
    {
        return redirect(route(''));
    }


    public function search(Request $request)
    {
        $equipment = $this->equipment->findEquipment($request['codebar']);
        $all = (new Equipment())->all();

        $sector = (new Sector())->all();

        return view('inventory.inventory_index', with([
            'equipment' => $equipment,
            'sectors' => $sector,
            'equipments' => $all,
        ]));
    }

    public function find($serial)
    {
        $equipment = $this->equipmentsRepository->customFind('serial_number', $serial);

        return view('inventory.inventory_show', with([
            'equipment' => $equipment,
        ]));
    }

    public function findSector(Request $request)
    {
        return $this->roomRepository->findRooms($request['sector']);
    }
}

app/Http/Controllers/Inventory/SectorController.php
<?php

namespace InvOco\Http\Controllers\Inventory;

use Illuminate\Http\Request;
use InvOco\Http\Controllers\Controller;

class SectorController extends Controller
{
    public function room($sector)
    {

    }
}

app/Http/Controllers/User/ActionController.php
<?php

namespace InvOco\Http\Controllers\User;

use Illuminate\Http\Request;
use InvOco\Http\Controllers\Controller;

class ActionController extends Controller
{
    //
}

app/Http/Controllers/User/LevelController.php
<?php

namespace InvOco\Http\Controllers\User;

use Illuminate\Http\Request;
use InvOco\Http\Controllers\Controller;
use InvOco\Repositories\Models\Level;

class LevelController extends Controller
{
    public function index()
    {
        $level = new Level();
        $levels = Level::all();

        return view('user.level.level', compact('levels', 'level'));
    }
}

app/Http/Controllers/User/UserController.php
<?php

namespace InvOco\Http\Controllers\User;

use Illuminate\Http\Request;
use InvOco\Http\Controllers\Controller;
use InvOco\Repositories\Models\Level;
use InvOco\Repositories\Models\User;

class UserController extends Controller
{
    public function index()
    {
        $users = User::all();

        return view('user.user_index', compact('users'));
    }

    public function create()
    {
        $user = new User();
        $levels = Level::all();

        return view('user.user_create', compact( 'user', 'levels'));
    }

    public function store(Request $request)
    {
        $data = $this->_validate($request);
        $data['password'] = bcrypt($data['password']);

        User::create($data);

        $users = User::all();

        return view ('user.user_index', compact( 'users'));
    }

    public function show($id)
    {
        $users = User::find($id);

        return view('user.user_show', compact('users'));
    }

    public function edit(User $user)
    {
        $levels = Level::all();

        return view('user.user_edit', compact('user', 'levels'));
    }

    public function update(Request $request, User $user)
    {
        $data = $this->_validate($request);
        $data['password'] = bcrypt($data['password']);

        $user->fill($data);
        $user->save();
        return redirect()->route('user.index');
    }

    public function destroy($id)
    {
        $users = User::find($id);
        $users->delete();

        return redirect()->route('user.index');
    }

    protected function _validate(Request $request)
    {
        $user = $request->route('user');
        $userId = $user instanceof User?$user->user:null;

        $rules = [
            'user' => "required|max:191|unique:user,user,$userId,user",
            'name' => 'required|max:100',
            'email' => 'required|email',
            'password' => 'required|min:6',
            'id_level' => 'required',
        ];

        return $this->validate($request, $rules);
    }
}

resources/views/inventory/form_inventory.blade.php
{{ csrf_token() }}
<div class="form-group">
    {{ Form::label('codebar', trans('inventory.barcode').":") }}
    {{ Form::text('codebar', old('codebar', $equipment->codebar), ['class' => 'form-control', 'placeholder' => trans('inventory.barcode'), 'value' => $equipment->codebar]) }}
</div>

<div class="form-group">
    {{ Form::label('serial_number', trans('inventory.serial_number').":") }}
    {{ Form::text('serial_number', old('serial_number', $equipment->serial_number), ['class' => 'form-control', 'placeholder' => trans('inventory.serial_number'), 'value' => $equipment->serial_number]) }}
</div>

<div class="form-group">
    {{ Form::label('item', 'Item:') }}
    {{ Form::text('item', old('item', $equipment->item ), ['class' => 'form-control', 'placeholder' => 'Item', 'value' => $equipment->item]) }}
</div>

<div class="form-group">
    {{ Form::label('brand', trans('inventory.brand').":") }}
    {{ Form::text('brand', old('brand', $equipment->brand), ['class' => 'form-control', 'placeholder' => trans('inventory.brand'), 'value' => $equipment->brand]) }}
</div>

<div class="form-group">
    {{ Form::label('fabrication_model', trans('inventory.model').":") }}
    {{ Form::text('fabrication_model', old('fabrication_model', $equipment->fabrication_model), ['class' => 'form-control', 'placeholder' => trans('inventory.model'), 'value' => $equipment->fabrication_model]) }}
</div>

<div class="form-group">
    {{ Form::label('id_type', trans('inventory.type').":") }}
    <select name="id_type" id="id_type" class="form-control sector">
        @foreach($type as $t)
            <option value="{{ $t->id_type }}">{{ $t->type }}</option>
        @endforeach
    </select>
</div>

<div class="form-group">
    {{ Form::label('id_sector', trans('inventory.sector').":") }}
    <select name="id_sector" id="id_sector" class="form-control sector">
        @foreach($sector as $s)
            <option value="{{ $s->sector }}">{{ $s->sector }}</option>
        @endforeach
    </select>
</div>

<div class="form-group">
    {{ Form::label('id_room', trans('inventory.room').":") }}
    <select name="id_room" id="id_room" class="form-control sector">

    </select>
</div>

<div class="form-group">
    {{ Form::label('obs', "Obs:") }}
    {{ Form::textarea('obs', old('obs', $equipment->obs), ['class' => 'form-control', 'placeholder' => "Obs", 'value' => $equipment->obs, 'rows' => '5']) }}
</div>

<div class="form-group">
    {{ Form::label('image', trans('inventory.image').":") }}
    {{ Form::text('image', old('image', $equipment->image), ['class' => 'form-control', 'placeholder' => trans('inventory.image'), 'value' => $equipment->image, 'v-model' => 'img']) }}
</div>

<div class="form-group">
    <a href="@{{ img }}" data-lightbox="lb"><img id="image" name="image" src="@{{ img }}" class="img-responsive"></a>
</div>

<div class="form-group">
    {{ Form::label('document', trans('inventory.documents').":") }}
    <input type="file" id="document" name="document">
</div>

resources/views/inventory/inventory_create.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                {{ trans('inventory.inventory') }}
            </h1>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-lg-12">
                    {{ Form::open(['url' => route('inventory.store'), 'method' => 'post']) }}
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title">{{ trans('others.insert') }} {{ trans('inventory.equipment') }}</h3>
                            </div>

                            <div class="box-body">
                                @include('inventory.form_inventory')
                            </div>

                            <div class="box-footer">
                                <button type="submit" class="btn btn-success btn-lg"><i class="fa fa-save"></i>&nbsp; {{ trans('others.insert') }}</button>
                            </div>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </section>
    </div>
@endsection

@section('js')
    <script src="{{ asset('js/vue-app.js') }}"></script>
@stop

resources/views/inventory/inventory_show.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                {{ trans('inventory.inventory') }}
            </h1>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">{{ trans('inventory.equipment') }}</h3>
                        </div>

                        <div class="box-body">
                            <table class="table table-bordered table-striped table-hover">
                                <tr>
                                    <th scope="row">{{ trans('inventory.serial_number') }}</th>
                                    <td>{{ $equipment->serial_number }}</td>
                                </tr>

                                <tr>
                                    <th scope="row">{{ trans('inventory.barcode') }}</th>
                                    <td>{{ $equipment->codebar }}</td>
                                </tr>

                                <tr>
                                    <th scope="row">Item</th>
                                    <td>{{ $equipment->item }}</td>
                                </tr>

                                <tr>
                                    <th scope="row">{{ trans('inventory.brand') }}</th>
                                    <td>{{ $equipment->brand }}</td>
                                </tr>

                                <tr>
                                    <th scope="row">{{ trans('inventory.model') }}</th>
                                    <td>{{ $equipment->fabrication_model }}</td>
                                </tr>

                                <tr>
                                    <th scope="row">{{ trans('inventory.type') }}</th>
                                    <td>{{ $equipment->type->type }}</td>
                                </tr>

                                <tr>
                                    <th scope="row">{{ trans('inventory.sector') }}</th>
                                    <td>{{ $equipment->sector->sector }}</td>
                                </tr>

                                <tr>
                                    <th scope="row">{{ trans('inventory.room') }}</th>
                                    <td>{{ $equipment->room->room }}</td>
                                </tr>

                                <tr>
                                    <th scope="row">{{ trans('others.created_at') }}</th>
                                    <td>{{ $equipment->created_at->format('d/m/Y - h:i:s') }}</td>
                                </tr>

                                <tr>
                                    <th scope="row">{{ trans('others.updated_at') }}</th>
                                    <td>{{ $equipment->updated_at->format('d/m/Y - h:i:s') }}</td>
                                </tr>

                                @if ($equipment->deleted_at)
                                <tr>
                                    <th scope="row">{{ trans('others.deleted_at') }}</th>
                                    <td>{{ $equipment->deleted_at->format('d/m/Y - h:i:s') }}</td>
                                </tr>
                                @else
                                <tr>
                                    <th scope="row">{{ trans('others.deleted_at') }}</th>
                                    <td>-</td>
                                </tr>
                                @endif

                                <tr>
                                    <th scope="row">Obs</th>
                                    <td>{{ $equipment->obs }}</td>
                                </tr>

                                <tr>
                                    <th scope="row">{{ trans('inventory.image') }}</th>
                                    <td><a href="{{ $equipment->image }}" data-lightbox="lb"><img id="image" name="image" src="{{ $equipment->image }}" title="{{ $equipment->item }}" alt="{{ $equipment->item }}" class="img-responsive"></a></td>
                                </tr>
                            </table>
                        </div>

                        <div class="box box-footer">
                            <a href="#" class="btn btn-warning"><i class="fa fa-pencil-square-o"></i> {{ trans("others.edit") }}</a>
                            <a href="#" class="btn btn-danger" onclick="event.preventDefault();if(confirm('{{ trans('user.delete') }}')){document.getElementById('form-delete').submit();}"><i class="fa fa-times"></i> {{ trans('others.delete') }}</a>
                            <form id="form-delete" style="display: none" action="{{ route('user.destroy', ['user' => $equipment->serial_number]) }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/menus/top_menu.blade.php
@php
    $profile = \InvOco\Repositories\Models\User::getUser();
@endphp
<header class="main-header">
    <a href="{{ route('dashboard') }}" class="logo">
        <span class="logo-mini"><strong>IO</strong></span>
        <span class="logo-lg"><strong>InvOco</strong></span>
    </a>

    <nav class="navbar navbar-static-top">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-user"></i><span class="hidden-xs"> {{ $profile->name }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ route('user.update', ['id' => $profile->user]) }}" class="btn btn-default btn-flat"><i class="fa fa-user"></i> {{ trans('user.profile') }}</a>
                            </div>
                            <div class="pull-right">
                                <a class="btn btn-default btn-flat" data-toggle="modal" data-target="#logoutModal"><i class="fa fa-fw fa-sign-out"></i>Logout</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

@include('menus.side_menu')

resources/views/user/level/form_level.blade.php
@include('errors.form_errors')
<div class="form-group">
    <label for="level">{{ trans('user.level') }}:</label>
    <input type="text" id="level" name="level" placeholder="{{ trans('user.level') }}" value="{{ old('level', $level->level) }}" class="form-control">
</div>

resources/views/user/level/level.blade.php
@extends('layouts.app')

@section('content')
    @include('menus.menu_user')

    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        {{ trans('user.levels') }} <small>{{ trans('others.data') }}</small>
                    </h1>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-4">
                    <h4 class="text-center">Consultar</h4>
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th class="text-center">{{ trans('user.level') }}</th>
                                <th class="text-center">{{ trans('others.actions') }}</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($levels as $l)
                                <tr>
                                    <td class="text-center">{{ $l->level }}</td>
                                    <td class="text-center" width="1%" nowrap="">
                                        <a href="#" class="btn btn-default btn-xs"><i class="fa fa-pencil-square-o"></i> {{ trans('others.edit') }}</a>
                                        <a href="{{ route('user.edit', ['user' => $l->level]) }}" class="btn btn-default btn-xs" onclick="event.preventDefault();if(confirm('{{ trans('user.level_delete') }}')){document.getElementById('form-delete').submit();}"><i class="fa fa-times"></i> {{ trans('others.delete') }}</a>
                                        <form id="form-delete" style="display: none" action="{{ route('user.edit', ['user' => $l->level]) }}" method="post">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>

                <div class="col-lg-4">
                    <h4 class="text-center">Cadastrar</h4>

                    <form id="frmCadastrar" name="frmCadastrar" method="post" action="/admin/level">
                        @include('user.level.form_level')
                        <input type="submit" id="btnCadastrar" name="btnCadastrar" value="{{ trans('others.insert') }}" class="btn btn-success">
                    </form>
                </div>

                <div class="col-lg-4">
                    <h4 class="text-center">Editar</h4>
                    <form id="frmEditar" name="frmEditar" method="post" action="/admin/level">
                        @include('user.level.form_level')
                        <input type="submit" id="btnEditar" name="btnEditar" value="{{ trans('others.edit') }}" class="btn btn-warning">
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/user_create.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                {{ trans('user.users') }}
                <small>{{ trans('others.data') }}</small>
            </h1>
        </section>

        <section class="content">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ trans('others.insert') }} {{ trans('user.user') }}</h3>
                </div>

                <div class="box-body">
                    @include('errors.form_errors')
                    {{ Form::open(['url' => route('user.store'), 'method' => 'post']) }}
                        @include('user.form_user')
                        {{ Form::submit(trans('others.insert')." ".trans('user.user'), ['class' => 'btn btn-success']) }}
                        <a href="{{ route('user.index') }}" class="btn btn-primary">Voltar</a>
                    {{ Form::close() }}
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/user/user_edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                {{ trans('user.users') }}
                <small>{{ trans('others.data') }}</small>
            </h1>
        </section>

        <section class="content">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ trans('others.edit') }} {{ trans('user.user') }}</h3>
                </div>

                <div class="box-body">
                    @include('errors.form_errors')
                    {{ Form::open(['url' => route('user.update', ['user' => $user->user]), 'method' => 'put']) }}
                        @include('user.form_user')
                        {{ Form::submit(trans('others.edit')." ".trans('user.user'), ['class' => 'btn btn-warning']) }}
                        <a href="{{ route('user.index') }}" class="btn btn-primary">Voltar</a>
                    {{ Form::close() }}
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/user/user_index.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                {{ trans('user.users') }}
                <small>{{ trans('others.data') }}</small>
            </h1>
        </section>

        <section class="content">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ trans('others.actions') }}</h3>
                </div>

                <div class="box-body">
                    <div class="btn-group">
                        <a href="{{ route('user.create') }}" class="btn btn-success"><i class="fa fa-plus"></i> {{ trans('others.insert') }} {{ trans('user.user') }}</a>

                        <a href="{{ route('user.create') }}" class="btn btn-primary"><i class="fa fa-tags"></i> {{ trans('user.levels') }}</a>

                        <a href="{{ route('user.create') }}" class="btn btn-primary"><i class="fa fa-tags"></i> {{ trans('others.actions') }}</a>
                    </div>
                </div>
            </div>

            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ trans('user.users') }} {{ trans('others.registered') }}</h3>
                </div>

                <div class="box-body">
                    <table class="table table-bordered table-striped table-hover dataTable">
                        <thead>
                        <tr>
                            <th class="text-center">{{ trans('user.user') }}</th>
                            <th class="text-center">{{ trans('user.name') }}</th>
                            <th class="text-center">E-mail</th>
                            <th class="text-center">{{ trans('user.profile') }}</th>
                            <th class="text-center">{{ trans('others.actions') }}</th>
                        </tr>
                        </thead>

                        <tbody>
                        @foreach($users as $u)
                            <tr>
                                <td class="text-center">{{ $u->user }}</td>
                                <td class="text-center">{{ $u->name }}</td>
                                <td class="text-center">{{ $u->email }}</td>
                                <td class="text-center">{{ $u->levels->level }}</td>
                                <td class="text-center" width="1%" nowrap="">
                                    <a href="{{ route('user.edit', ['user' => $u->user]) }}" class="btn btn-default btn-xs"><i class="fa fa-pencil-square-o"></i> {{ trans('others.edit') }}</a>
                                    <a href="{{ route('user.show', ['user' => $u->user]) }}" class="btn btn-default btn-xs"><i class="fa fa-search"></i> {{ trans('others.view') }}</a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/user/user_show.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                {{ trans('user.users') }}
                <small>{{ trans('others.data') }}</small>
            </h1>
        </section>

        <section class="content">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">{{ trans('others.view') }} {{ trans('user.user') }}</h3>
                </div>

                <div class="box-body">
                    <table class="table table-bordered table-striped table-hover dataTable">
                        <tr>
                            <th scope="row">{{ trans('user.user') }}</th>
                            <td>{{ $users->user }}</td>
                        </tr>

                        <tr>
                            <th scope="row">{{ trans('user.name') }}</th>
                            <td>{{ $users->name }}</td>
                        </tr>

                        <tr>
                            <th scope="row">E-mail</th>
                            <td>{{ $users->email }}</td>
                        </tr>

                        <tr>
                            <th scope="row">{{ trans('user.profile') }}</th>
                            <td>{{ $users->levels->level }}</td>
                        </tr>
                    </table>

                    <br/>

                    <a href="{{ route('user.destroy', ['user' => $users->user]) }}" class="btn btn-danger" onclick="event.preventDefault();if(confirm('{{ trans('user.delete') }}')){document.getElementById('form-delete').submit();}">{{ trans('others.delete') }}</a>
                    <a href="{{ route('user.index') }}" class="btn btn-primary">Voltar</a>
                    <form id="form-delete" style="display: none" action="{{ route('user.destroy', ['user' => $users->user]) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                    </form>
                </div>

            </div>
        </section>
    </div>
@endsection